title: Tuist
email: pepibumur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tuist is a tool that helps developers manage large Xcode projects by leveraging
  project generation. Moreover, it provides some tools to automate most common tasks, allowing
  developers to focus on building app.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tuist.io"
twitter_username: tuistapp
github_username:  tuist
sass:
  sass_dir: _sass

urls:
  releases: https://github.com/tuist/tuist/releases
  github: https://github.com/tuist
  contributors: https://github.com/orgs/tuist/teams/contributors
  pedro: https://ppinera.com
  open_pr: https://github.com/tuist/website
  patreon: https://www.patreon.com/tuist

markdown: kramdown
plugins:
  - jekyll-feed
  - pagemaster
collections:
  guides:
    output: true
    permalink: /:collection/:name
  docs:
    output: true
    source: docs.yml
    id_key: id
    layout: doc
collections_dir: collections
permalink: /blog/:year/:month/:day/:title/